#ifndef _PARAMS_FOR_EXPERIMENTS_H_
#define _PARAMS_FOR_EXPERIMENTS_H_

#include "rg_Const.h"

// test
//rg_REAL ALPHA_COEFF_COMBINATORIAL_SEARCH = 1.0;
//rg_REAL RADIUS_INFLATION_RATE = 0.0;
//
//rg_FLAG THIRD_OR_FARTHER_VORONOI_NEIGHBORS_TO_SEARCH = rg_FALSE;

#endif